plugins:
  - rubocop-performance

AllCops:
  DisabledByDefault: true
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - "coverage/**/*"
    - "vendor/**/*"
    - "tmp/**/*"

Performance:
  Enabled: true
