# frozen_string_literal: true

module RubyGBA
  module Calibration
    # Renders the cartridges a calibration measured as the Ruby source of
    # tools/calibration/measured_cartridges.rb. Pure string work — two hashes in, source out —
    # so what it writes can be asserted without running a calibration.
    #
    # A sibling of {WeightsFixture} and deliberately NOT part of it. The weights are loaded by
    # every build that prices a program; this is provenance for the tool, read only by the check
    # that says whether the weights are still current. Folding a hundred and fifty lines of
    # digests into the file the library requires would put them in the path of every cartridge
    # anybody builds, for nothing.
    class CartridgesFixture
      INDENT = " " * 4 # inside `module Calibration`
      ROW = " " * 6    # inside a hash literal

      def initialize(digests:, emulator:)
        @digests = digests
        @emulator = emulator
      end

      def render
        "#{(header + body).join("\n")}\n"
      end

      private

      def header
        [
          "# frozen_string_literal: true",
          "#",
          "# GENERATED by tools/calibrate_cost_model.rb — do not edit by hand.",
          "#",
          "# The cartridges the committed weights were measured on, by content. The emulator is",
          "# deterministic, so a cartridge that has not changed cannot read differently — and one",
          "# that HAS changed may, which means whatever weight it fed is now describing code the",
          "# build no longer emits.",
          "#",
          "# Nothing at run time reads this. It is here so the suite can rebuild every cartridge",
          "# and say, without an emulator, whether the weights beside it are still the ones this",
          "# tree would measure. When it says they are not, re-run the tool: it prints every",
          "# weight that moved and by how much. See tools/calibration/provenance.rb.",
        ]
      end

      def body
        ["module RubyGBA", "  module Calibration"] +
          hash_literal("MEASURED_CARTRIDGES", digest_rows) +
          ["", "#{INDENT}# The emulator that read them (its own sources, in one digest).",
           "#{INDENT}MEASURED_EMULATOR = #{@emulator.inspect}"] +
          ["  end", "end"]
      end

      def hash_literal(name, rows)
        ["#{INDENT}#{name} = {"] + rows + ["#{INDENT}}.freeze"]
      end

      # Sorted by name, not by the order the benchmarks happened to run in: a diff should show
      # the cartridges that changed, not that the recipes were reordered.
      def digest_rows
        @digests.sort.map { |name, hex| "#{ROW}#{name.inspect} => #{hex.inspect}," }
      end
    end
  end
end
