# frozen_string_literal: true

module RubyGBA
  module Calibration
    # Renders the measured weights (and where each was measured) as the Ruby source of
    # lib/ruby_gba/ir/measured_weights.rb. Pure string work — a hash in, source out — so what
    # it writes can be asserted without running a calibration.
    #
    # A generated Ruby file rather than JSON or YAML because the cost model loads it like any
    # other constant: no parsing, no file lookup at run time, and a diff a person reads.
    #
    # Built line by line rather than from one big template, because the domains section is
    # optional and threading that through a heredoc's indentation is a good way to ship a file
    # that only looks right.
    class WeightsFixture
      # Five decimals, because the smallest weight is a per-pixel transfer near 0.001 — at four
      # it would keep two significant figures and at three it would round to nothing.
      PLACES = 5
      INDENT = " " * 6 # inside `class CostModel`
      ROW = " " * 8    # inside a hash literal

      def initialize(weights:, domains: {})
        @weights = weights
        @domains = domains
      end

      def render
        "#{(header + body).join("\n")}\n"
      end

      private

      def header
        lines = [
          "# frozen_string_literal: true",
          "#",
          "# GENERATED by tools/calibrate_cost_model.rb — do not edit by hand.",
          "# Re-run that tool after changing the lowering of a priced op, and commit the diff.",
          "# Each value is scanlines per op, measured on the emulated GBA timing model via",
          "# gemba-core (emulated-cycle counts, not host wall-clock — the same on any machine).",
        ]
        lines + (@domains.empty? ? [] : domains_preamble)
      end

      # Why the ranges are there at all. Worth saying in the generated file itself, because this
      # is the file somebody opens when they want to know what a weight means.
      def domains_preamble
        [
          "#",
          "# WEIGHT_DOMAINS records where each weight was MEASURED, which is where it can be",
          "# trusted. Nearly every weight is a marginal rate — two ROMs differenced over how",
          "# many of the thing they do — and that cancels whatever the thing pays only ONCE. So",
          "# a rate measured over a loop of 300..900 passes says nothing about a loop of 4, and",
          "# the model uses these ranges to say so out loud instead of answering confidently.",
          "# An empty range means the weight has no countable regime: an add costs what an add",
          "# costs, and no number in a program changes it. See tools/calibration/domain.rb.",
        ]
      end

      def body
        inner = hash_literal("MEASURED_WEIGHTS", weight_rows)
        inner += [""] + hash_literal("WEIGHT_DOMAINS", domain_rows) unless @domains.empty?
        ["module RubyGBA", "  module IR", "    class CostModel"] + inner + ["    end", "  end", "end"]
      end

      def hash_literal(name, rows)
        ["#{INDENT}#{name} = {"] + rows + ["#{INDENT}}.freeze"]
      end

      def weight_rows
        @weights.map { |name, value| "#{ROW}#{name}: #{format("%.#{PLACES}f", value)}," }
      end

      def domain_rows
        @weights.keys.map { |name| "#{ROW}#{name}: #{(@domains[name]&.to_source) || '{}'}," }
      end
    end
  end
end
