# frozen_string_literal: true

module RubyGBA
  module Calibration
    # Renders the measured weights (and where each was measured) as the Ruby source of
    # lib/ruby_gba/ir/measured_weights.rb. Pure string work — a hash in, source out — so what
    # it writes can be asserted without running a calibration.
    #
    # A generated Ruby file rather than JSON or YAML because the cost model loads it like any
    # other constant: no parsing, no file lookup at run time, and a diff a person reads.
    #
    # Built line by line rather than from one big template, because the domains section is
    # optional and threading that through a heredoc's indentation is a good way to ship a file
    # that only looks right.
    class WeightsFixture
      # Five decimals, because the smallest weight is a per-pixel transfer near 0.001 — at four
      # it would keep two significant figures and at three it would round to nothing.
      PLACES = 5
      INDENT = " " * 6 # inside `class CostModel`
      ROW = " " * 8    # inside a hash literal

      def initialize(weights:, domains: {}, gains: {})
        @weights = weights
        @domains = domains
        @gains = gains
      end

      def render
        "#{(header + body).join("\n")}\n"
      end

      private

      def header
        lines = [
          "# frozen_string_literal: true",
          "#",
          "# GENERATED by tools/calibrate_cost_model.rb — do not edit by hand.",
          "# Re-run that tool after changing the lowering of a priced op, and commit the diff.",
          "# You do not have to remember to: the suite rebuilds every cartridge these numbers",
          "# were measured on and fails when they are no longer the ones this tree builds.",
          "# Each value is scanlines per op, measured on the emulated GBA timing model via",
          "# gemba-core (emulated-cycle counts, not host wall-clock — the same on any machine).",
        ]
        lines + (@domains.empty? ? [] : domains_preamble) + (@gains.empty? ? [] : gains_preamble)
      end

      # ...and why the gains are there, which is the thing a reader of this file is most likely
      # to be surprised by: there is no single figure for what the console's quick memory buys.
      def gains_preamble
        [
          "#",
          "# MEASURED_GAINS is how many times faster each op runs when the build keeps its code",
          "# in the console's quick memory. There is no one figure: the quick memory makes",
          "# FETCHING an instruction cheap and does nothing for a load or a store, so an op that",
          "# stays in registers gains about four times and one that is mostly memory gains about",
          "# half of that. Measured by running every recipe above a second time with the build",
          "# free to move the code, and dividing.",
          "#",
          "# A weight with no line here keeps the general figure (fast_code_speedup). Those are",
          "# the ones whose recipe is a difference of differences, which can land near zero in",
          "# one of the two runs and give a ratio that is an artefact rather than a measurement.",
        ]
      end

      # Why the ranges are there at all. Worth saying in the generated file itself, because this
      # is the file somebody opens when they want to know what a weight means.
      def domains_preamble
        [
          "#",
          "# WEIGHT_DOMAINS records where each weight was MEASURED, which is where it can be",
          "# trusted. Nearly every weight is a marginal rate — two ROMs differenced over how",
          "# many of the thing they do — and that cancels whatever the thing pays only ONCE. So",
          "# a rate measured over a loop of 300..900 passes says nothing about a loop of 4, and",
          "# the model uses these ranges to say so out loud instead of answering confidently.",
          "# An empty range means the weight has no countable regime: an add costs what an add",
          "# costs, and no number in a program changes it. See tools/calibration/domain.rb.",
        ]
      end

      def body
        inner = hash_literal("MEASURED_WEIGHTS", weight_rows)
        inner += [""] + hash_literal("WEIGHT_DOMAINS", domain_rows) unless @domains.empty?
        # Always written, even empty: the cost model reads it as a constant, so a run that
        # measured no gain has to leave a hash rather than nothing to load.
        inner += [""] + hash_literal("MEASURED_GAINS", gain_rows)
        ["module RubyGBA", "  module IR", "    class CostModel"] + inner + ["    end", "  end", "end"]
      end

      def hash_literal(name, rows)
        ["#{INDENT}#{name} = {"] + rows + ["#{INDENT}}.freeze"]
      end

      def weight_rows
        @weights.map { |name, value| "#{ROW}#{name}: #{format("%.#{PLACES}f", value)}," }
      end

      def domain_rows
        @weights.keys.map { |name| "#{ROW}#{name}: #{(@domains[name]&.to_source) || '{}'}," }
      end

      # In the weights' own order, so the two hashes read side by side and a weight with no
      # measurable gain is a visible hole rather than a silently missing row.
      def gain_rows
        @weights.keys.filter_map do |name|
          gain = @gains[name] or next

          "#{ROW}#{name}: #{format('%.3f', gain)},"
        end
      end
    end
  end
end
