# frozen_string_literal: true

require "json"
require_relative "../asm" # what building a constant costs decides part of what drawing costs
require_relative "../constants" # where the picture lives, for the same reason
require_relative "printer"
require_relative "measured_weights" # MEASURED_WEIGHTS, generated by tools/calibrate_cost_model.rb
require_relative "cost_model/pricing"
require_relative "cost_model/rollup"
require_relative "cost_model/tree"
require_relative "cost_model/verdicts"
require_relative "cost_model/report"

module RubyGBA
  module IR
    # Estimates how much per-frame work a program does — mostly drawing, plus the
    # sound work that shares the same frame — per frame for a game loop, or once at
    # boot for a static program. It's the engine behind the render-budget guardrail
    # and `rom.explain`: a program that does more each frame than the console can
    # finish before the screen refreshes will tear, and this is how we spot that
    # before it ever runs on hardware.
    #
    # Costs are in *scanlines* — the console draws the screen one scanline at a time,
    # so a scanline of drawing time is the natural unit, and the vertical blank (the
    # safe window to draw before the picture tears) is about 68 scanlines. So "this
    # frame costs 45 scanlines" means "it eats 45 of your ~68 safe scanlines." Weights
    # are calibrated with the timing probe (gemba-core), which counts the cycles a known
    # workload actually burns in a frame of the emulator's GBA timing model — see
    # tools/calibrate_cost_model.rb, which measures each one and is re-run whenever the
    # lowering of a priced op changes. Every weight is measured that way — the logic
    # steps, plot_pixel, sound_write, the mixer, music, both parts of a DMA fill (what
    # STARTING a row's transfer costs — on the CPU and in the engine, which is stalled
    # time the CPU never executes — and the per-pixel transfer on top), sprite/scroll
    # upkeep, and per-pixel collision. A game dev can override any of them.
    #
    # Two things drive the cost. Drawing is dominated by DMA *operations*: a fill, a
    # blit, a save/restore is one DMA per row, and the per-row setup dwarfs the
    # per-pixel transfer — so a wide row and a narrow one cost about the same, and
    # cost scales with a rectangle's height (rows), not its area. And a pixel written
    # one at a time is far dearer than one moved by DMA — so an opaque image streams
    # cheaply while a transparent one, drawn pixel by pixel, does not. Sound is priced
    # in the same scanline unit.
    #
    # "One at a time" is itself three prices, not one, because what the console has to
    # work out before each write differs: a LONE pixel builds a whole address and
    # fetches its color (plot_pixel); a pixel of a RUN — a fixed-size fill, a font
    # glyph — has the color in hand and its address settled while building, so it is
    # cheaper (plot_run_pixel); and a pixel of a SOFTWARE SPRITE, whose position the
    # game works out, is tested against the screen edges on its own first, so it is
    # dearer than either (blit_pixel). See {Pricing}#blit_cost.
    #
    # What the model gets exactly right is the *shape* of the work: a loop's body
    # counts once per iteration, a list-driven loop counts up to the list's capacity
    # (the worst it can reach), and a scene dispatch (case_var) costs its heaviest
    # branch, since only one branch runs per frame.
    #
    # #analyze returns the work as a structured tree (op, label, cost, children) —
    # the shape rom.explain renders for humans and dumps as JSON for tests.
    #
    # Selectivity — that `every(6)` only draws one frame in six, that a `draw_number`
    # column stays blank until the number reaches its place, so a four-column score
    # showing "12" draws two digits and not four — is a later layer that reads semantic
    # tags off the IR; today every branch is counted at full weight. That is the safe way
    # to be wrong (a score field is sized for the number it will eventually hold, and then
    # every column does draw), but it is why a game whose score is still small reads a
    # little over.
    #
    # The work is split by the question each part answers, one file each:
    #
    #   {Pricing}   what does one op cost?
    #   {Rollup}    how many times does a frame pay for it?
    #   {Tree}      how does that read to a person? (folding, grouping, pruning)
    #   {Verdicts}  does it fit, and what can't the estimate see?
    #   {Report}    print it, or hand it back as a Hash
    #
    # This file is the class itself: the shared constants and the weights. A constant
    # only one part uses lives with that part.
    class CostModel
      include Pricing
      include Rollup
      include Tree
      include Verdicts
      include Report

      SCREEN_W = 240
      SCREEN_H = 160

      # Where the picture lives in memory, and how much of it one direct-color pixel takes.
      # Both are here because how far into the picture a pixel sits decides how many steps
      # the console spends working out its address, and that is a real part of what drawing
      # costs — see {Pricing}#run_pixel_weight.
      FRAMEBUFFER_BASE = Constants::VRAM_START
      BYTES_PER_DIRECT_PIXEL = 2
      ARM_INSTRUCTION_BYTES = 4

      # The characters a run-time digit field can show — one of these draws.
      DIGITS = ("0".."9").to_a.freeze

      # How a report names one arithmetic operator it pulls out of the statement it sits
      # in: +op+ is the key the hottest list groups by, +name+ is the words a person
      # reads. See {Pricing}#arithmetic_kind for which operators get one and why.
      Arithmetic = Data.define(:op, :name)

      # What a `blit` needs to be priced, taken off the image's DEFINITION (the blit op
      # itself carries only a name and a position). Transparency is not a detail here:
      # an image with no see-through color streams onto the screen in whole rows, while
      # one with a see-through color is drawn a pixel at a time so the background shows
      # between them — and only its LIT pixels are drawn, on rows that have one.
      #
      # +wide_color_pixels+ is the share of those lit pixels whose color needs a step of
      # its own to build. Drawing one pixel at a time means writing the color into every
      # store, and only some colors fit inside the instruction that does it — so two
      # pictures of the same shape can differ by a tenth on their colors alone.
      # See {Rollup}#catalogue_bitmap for how the counts are taken.
      Bitmap = Data.define(:width, :height, :transparent, :lit_pixels, :wide_color_pixels, :lit_rows)

      # What drawing one hardware sprite needs to be priced, likewise taken off its
      # DECLARATION rather than the per-frame draw. A sprite that only moves is a
      # position written into a table. One that TURNS is drawn through a small matrix
      # instead, and that matrix is rebuilt from its angle every frame. One that also
      # RESIZES has to work out one over its size to build that matrix — a division,
      # done for the author, and the dearest part of drawing a sprite.
      #
      # Resizing implies turning: a sprite drawn at a size goes through the same matrix
      # whether or not its angle ever moves. See {Rollup}#catalogue_object.
      Sprite = Data.define(:turns, :resizes)

      # The per-frame drawing budget, in scanlines: the vertical blank — the safe
      # window to change the screen before the visible frame starts — is about 68 of
      # the console's 228 scanlines. Draw more than this in a single-buffered frame
      # and it tears.
      VBLANK_BUDGET = 68

      # The budget when the program double-buffers (draws to a hidden page shown all
      # at once): drawing isn't confined to the safe window, it can use the whole
      # frame (all 228 scanlines), and going over means a dropped frame (below
      # 60fps), never a tear.
      FRAME_BUDGET = 228

      # A ceiling on how much per-frame work a *single song* should cost on its own,
      # in scanlines. Playing a song re-checks every note against a frame counter on
      # every frame, so a long enough tune becomes real recurring work that has
      # nothing to do with drawing; past this the music guardrail flags it. (The
      # note-check cost itself is estimated, not measured — music timing is a
      # separate concern from the drawing the probe calibrated.)
      MUSIC_STEADY_BUDGET = 1.0

      # A sound op is a short burst of writes to the sound registers; these are the
      # write counts, priced in scanlines via the measured sound_write weight.
      # (Playing a song is priced separately — see #song_cost.)
      ENABLE_WRITES = 3  # power the sound hardware on
      BEEP_WRITES   = 2  # one channel-2 sound effect
      NOISE_WRITES  = 2  # one channel-4 percussion hit
      WAVE_WRITES   = 21 # a channel-3 tone: upload the wavetable to both banks + control
      STOP_WAVE_WRITES = 1 # silence the wave voice
      STOP_WRITES   = 4  # silence both music voices (channels 1 and 2)

      # The software mixer's per-frame CPU. When a program plays sampled sound, a
      # software mixer runs once every frame (right after wait_vblank), summing every
      # sounding voice into the output buffer — real recurring work the drawing budget
      # can't see. Unlike drawing, it's CPU work spread across the whole frame, not the
      # brief vblank window, so it's judged against the full frame (overrunning drops a
      # frame; it can't tear, since it touches no video memory). Its cost scales with
      # the buffer it fills each frame (the sample rate / 60) and the voices it sums,
      # priced at the worst case — the mixer's full voice count — the way the rest of
      # the model prices the heaviest a frame can reach.
      MIXER_VOICES = 8          # voices the mixer sums at once (mirrors the backend's capacity)
      MIXER_FPS = 60            # it refills one frame's worth of samples per frame
      DEFAULT_MIXER_RATE = 8192 # fallback output rate when no sample declares one

      # Bending a background row by row (`scroll_each_row`) is the other standing
      # per-frame cost, and the bigger one. The display asks where each row sits as it
      # draws it, so the framework answers once per line — which means the program is
      # interrupted after every line the display counts, all 228 of them, whether that
      # line is part of the picture or not. Only the visible ones need the program's own
      # offset worked out.
      #
      # Like the mixer, this happens every frame no matter what the game loop does, so it
      # is added to the frame rather than found in the op tree. It is CPU work spread
      # through the whole frame (it never touches video memory), so it is judged against
      # the whole frame and cannot tear.
      LINES_PER_FRAME = 228  # every line the display counts, picture or not — each one interrupts
      VISIBLE_LINES = 160    # the lines the picture is drawn on, where an offset is worked out

      # The default weights are the generated fixture — every priced op measured on the
      # emulator's GBA timing model by the calibration tool. Override per-call for
      # what-ifs: CostModel.new(op_step: 0.5). Re-run tools/calibrate_cost_model.rb to
      # remeasure.
      DEFAULT_WEIGHTS = MEASURED_WEIGHTS

      # Kinds that legitimately cost nothing per frame, so they fall through op_cost /
      # expr_cost without being flagged. Everything ELSE that falls through is a kind the
      # model doesn't know how to estimate — it gets counted as zero, which would hide
      # real work, so it's collected and announced instead (see #unpriced_kinds). This
      # is the split that keeps a newly-added op from slipping by as free: price it, or
      # declare it free here, or the estimate calls it out. (Control-flow kinds — loop,
      # if, case, call, and so on — never reach here; they're handled in #build.)
      FREE_STATEMENT_KINDS = %i[
        screen wait_vblank halt raw object
        define_sound song data bitmap backing_buffer list_new table
        timer_start timer_stop on_timer
        sample play_sample stop_sample
        # A row-by-row bend is a standing declaration, like a timer's handler: nothing
        # happens where it is written. Its real cost is per LINE, not per statement, so it
        # is priced once for the whole frame in #bend_verdict and rolled in beside the
        # mixer's — charging it here as well would count it twice.
        scroll_rows
        # loading the saved variables happens once at boot, before the first frame, so
        # it never lands on a frame's budget — like the declarations above it.
        save_init
      ].freeze
      FREE_VALUE_KINDS = %i[int var_ref data_byte list_get list_len table_get held pressed read_scanline timer_ticks].freeze

      # Every costed op falls into one of three buckets, so a frame's work reads as
      # drawing vs sound vs logic — the sections the estimate rolls up into. DRAWING is
      # the vblank-constrained work (writes to video memory), and it alone carries the
      # tear check. SOUND is the sound-register writes plus the software mixer. Anything
      # else the loop computes — moving things, collisions, counters — is LOGIC. They
      # all share the one frame, so they all roll into the frame total.
      # camera and fade redraw nothing — they tell the display where to look and how far
      # to blend — but they are still writes the visible frame must not see part-done, so
      # they belong with the drawing the tear check judges.
      DRAW_KINDS = %i[
        pixel fill_rect dma_fill_rect draw_rect_at clear_screen draw_text draw_digit
        blit blit_pose save_region restore_region present_objects scroll_background background
        camera fade
      ].freeze
      SOUND_KINDS = %i[play_song beep noise wave stop_wave enable_sound stop_music mixer].freeze
      CATEGORY_ORDER = %i[drawing sound logic].freeze

      # +fast_routines+ names the routines this build keeps in faster memory, and
      # +fast_frame+ says whether the frame's own body is one of them (it has no name of
      # its own). Their work is charged at #FAST_SPEEDUP less, because that is measured to
      # be how much faster the same instructions run there — see
      # Backends::GBA::Placement. Left out, nothing is discounted, which is what a target
      # with one kind of memory wants.
      # +fast_interrupts+ likewise says whether the routine an announcement is answered in
      # lives there. It is its own flag for the same reason the frame's body is: the program
      # has no name for it.
      # +placement+ is the whole picture for the report — which routines moved and how
      # much memory is used and left (see Backends::GBA::Placement#iwram_report).
      def initialize(fast_routines: nil, fast_frame: false, fast_interrupts: false,
                     placement: nil, **weights)
        @weights = DEFAULT_WEIGHTS.merge(weights)
        @fast_routines = Array(fast_routines).to_set
        @fast_frame = fast_frame
        @fast_interrupts = fast_interrupts
        @placement = placement
        @in_fast_code = false
      end
    end
  end
end
