# frozen_string_literal: true

require "json"
require_relative "../asm" # a blit bakes a color into every pixel; how dear that is depends on the encoding
require_relative "printer"
require_relative "measured_weights" # MEASURED_WEIGHTS, generated by tools/calibrate_cost_model.rb
require_relative "cost_model/pricing"
require_relative "cost_model/rollup"
require_relative "cost_model/tree"
require_relative "cost_model/verdicts"
require_relative "cost_model/report"

module RubyGBA
  module IR
    # Estimates how much per-frame work a program does — mostly drawing, plus the
    # sound work that shares the same frame — per frame for a game loop, or once at
    # boot for a static program. It's the engine behind the render-budget guardrail
    # and `rom.explain`: a program that does more each frame than the console can
    # finish before the screen refreshes will tear, and this is how we spot that
    # before it ever runs on hardware.
    #
    # Costs are in *scanlines* — the console draws the screen one scanline at a time,
    # so a scanline of drawing time is the natural unit, and the vertical blank (the
    # safe window to draw before the picture tears) is about 68 scanlines. So "this
    # frame costs 45 scanlines" means "it eats 45 of your ~68 safe scanlines." Weights
    # are calibrated with the timing probe (gemba-core), which counts the cycles a known
    # workload actually burns in a frame of the emulator's GBA timing model — see
    # tools/calibrate_cost_model.rb, which measures each one and is re-run whenever the
    # lowering of a priced op changes. Every weight is measured that way — the logic
    # steps, plot_pixel, sound_write, the mixer, music, both parts of a DMA fill (the
    # per-row CPU setup and the per-pixel transfer stall), sprite/scroll upkeep, and
    # per-pixel collision. A game dev can override any of them.
    #
    # Two things drive the cost. Drawing is dominated by DMA *operations*: a fill, a
    # blit, a save/restore is one DMA per row, and the per-row setup dwarfs the
    # per-pixel transfer — so a wide row and a narrow one cost about the same, and
    # cost scales with a rectangle's height (rows), not its area. And a pixel written
    # one at a time is far dearer than one moved by DMA — so an opaque image streams
    # cheaply while a transparent one, drawn pixel by pixel, does not. Sound is priced
    # in the same scanline unit.
    #
    # "One at a time" is itself three prices, not one, because what the console has to
    # work out before each write differs: a LONE pixel builds a whole address and
    # fetches its color (plot_pixel); a pixel of a RUN — a fixed-size fill, a font
    # glyph — has the color in hand and its address settled while building, so it is
    # cheaper (plot_run_pixel); and a pixel of a SOFTWARE SPRITE, whose position the
    # game works out, is tested against the screen edges on its own first, so it is
    # dearer than either (blit_pixel). See {Pricing}#blit_cost.
    #
    # What the model gets exactly right is the *shape* of the work: a loop's body
    # counts once per iteration, a list-driven loop counts up to the list's capacity
    # (the worst it can reach), and a scene dispatch (case_var) costs its heaviest
    # branch, since only one branch runs per frame.
    #
    # #analyze returns the work as a structured tree (op, label, cost, children) —
    # the shape rom.explain renders for humans and dumps as JSON for tests.
    #
    # Selectivity — that `every(6)` only draws one frame in six, that a
    # `draw_number` column draws one of ten glyphs — is a later layer that reads
    # semantic tags off the IR; today every branch is counted at full weight.
    #
    # The work is split by the question each part answers, one file each:
    #
    #   {Pricing}   what does one op cost?
    #   {Rollup}    how many times does a frame pay for it?
    #   {Tree}      how does that read to a person? (folding, grouping, pruning)
    #   {Verdicts}  does it fit, and what can't the estimate see?
    #   {Report}    print it, or hand it back as a Hash
    #
    # This file is the class itself: the shared constants and the weights. A constant
    # only one part uses lives with that part.
    class CostModel
      include Pricing
      include Rollup
      include Tree
      include Verdicts
      include Report

      SCREEN_W = 240
      SCREEN_H = 160

      # The characters a run-time digit field can show — one of these draws.
      DIGITS = ("0".."9").to_a.freeze

      # How a report names one arithmetic operator it pulls out of the statement it sits
      # in: +op+ is the key the hottest list groups by, +name+ is the words a person
      # reads. See {Pricing}#arithmetic_kind for which operators get one and why.
      Arithmetic = Data.define(:op, :name)

      # What a `blit` needs to be priced, taken off the image's DEFINITION (the blit op
      # itself carries only a name and a position). Transparency is not a detail here:
      # an image with no see-through color streams onto the screen in whole rows, while
      # one with a see-through color is drawn a pixel at a time so the background shows
      # between them — and only its LIT pixels are drawn, on rows that have one.
      #
      # +wide_color_pixels+ is the share of those lit pixels whose color needs a step of
      # its own to build. Drawing one pixel at a time means writing the color into every
      # store, and only some colors fit inside the instruction that does it — so two
      # pictures of the same shape can differ by a tenth on their colors alone.
      # See {Rollup}#catalogue_bitmap for how the counts are taken.
      Bitmap = Data.define(:width, :height, :transparent, :lit_pixels, :wide_color_pixels, :lit_rows)

      # The per-frame drawing budget, in scanlines: the vertical blank — the safe
      # window to change the screen before the visible frame starts — is about 68 of
      # the console's 228 scanlines. Draw more than this in a single-buffered frame
      # and it tears.
      VBLANK_BUDGET = 68

      # The budget when the program double-buffers (draws to a hidden page shown all
      # at once): drawing isn't confined to the safe window, it can use the whole
      # frame (all 228 scanlines), and going over means a dropped frame (below
      # 60fps), never a tear.
      FRAME_BUDGET = 228

      # A ceiling on how much per-frame work a *single song* should cost on its own,
      # in scanlines. Playing a song re-checks every note against a frame counter on
      # every frame, so a long enough tune becomes real recurring work that has
      # nothing to do with drawing; past this the music guardrail flags it. (The
      # note-check cost itself is estimated, not measured — music timing is a
      # separate concern from the drawing the probe calibrated.)
      MUSIC_STEADY_BUDGET = 1.0

      # A sound op is a short burst of writes to the sound registers; these are the
      # write counts, priced in scanlines via the measured sound_write weight.
      # (Playing a song is priced separately — see #song_cost.)
      ENABLE_WRITES = 3  # power the sound hardware on
      BEEP_WRITES   = 2  # one channel-2 sound effect
      NOISE_WRITES  = 2  # one channel-4 percussion hit
      WAVE_WRITES   = 21 # a channel-3 tone: upload the wavetable to both banks + control
      STOP_WAVE_WRITES = 1 # silence the wave voice
      STOP_WRITES   = 4  # silence both music voices (channels 1 and 2)

      # The software mixer's per-frame CPU. When a program plays sampled sound, a
      # software mixer runs once every frame (right after wait_vblank), summing every
      # sounding voice into the output buffer — real recurring work the drawing budget
      # can't see. Unlike drawing, it's CPU work spread across the whole frame, not the
      # brief vblank window, so it's judged against the full frame (overrunning drops a
      # frame; it can't tear, since it touches no video memory). Its cost scales with
      # the buffer it fills each frame (the sample rate / 60) and the voices it sums,
      # priced at the worst case — the mixer's full voice count — the way the rest of
      # the model prices the heaviest a frame can reach.
      MIXER_VOICES = 8          # voices the mixer sums at once (mirrors the backend's capacity)
      MIXER_FPS = 60            # it refills one frame's worth of samples per frame
      DEFAULT_MIXER_RATE = 8192 # fallback output rate when no sample declares one

      # The default weights are the generated fixture — every priced op measured on the
      # emulator's GBA timing model by the calibration tool. Override per-call for
      # what-ifs: CostModel.new(op_step: 0.5). Re-run tools/calibrate_cost_model.rb to
      # remeasure.
      DEFAULT_WEIGHTS = MEASURED_WEIGHTS

      # Kinds that legitimately cost nothing per frame, so they fall through op_cost /
      # expr_cost without being flagged. Everything ELSE that falls through is a kind the
      # model doesn't know how to estimate — it gets counted as zero, which would hide
      # real work, so it's collected and announced instead (see #unpriced_kinds). This
      # is the split that keeps a newly-added op from slipping by as free: price it, or
      # declare it free here, or the estimate calls it out. (Control-flow kinds — loop,
      # if, case, call, and so on — never reach here; they're handled in #build.)
      FREE_STATEMENT_KINDS = %i[
        screen wait_vblank halt raw object
        define_sound song data bitmap backing_buffer list_new table
        timer_start timer_stop on_timer
        sample play_sample stop_sample
        # loading the saved variables happens once at boot, before the first frame, so
        # it never lands on a frame's budget — like the declarations above it.
        save_init
      ].freeze
      FREE_VALUE_KINDS = %i[int var_ref data_byte list_get list_len table_get held pressed read_scanline timer_ticks].freeze

      # Every costed op falls into one of three buckets, so a frame's work reads as
      # drawing vs sound vs logic — the sections the estimate rolls up into. DRAWING is
      # the vblank-constrained work (writes to video memory), and it alone carries the
      # tear check. SOUND is the sound-register writes plus the software mixer. Anything
      # else the loop computes — moving things, collisions, counters — is LOGIC. They
      # all share the one frame, so they all roll into the frame total.
      # camera and fade redraw nothing — they tell the display where to look and how far
      # to blend — but they are still writes the visible frame must not see part-done, so
      # they belong with the drawing the tear check judges.
      DRAW_KINDS = %i[
        pixel fill_rect dma_fill_rect draw_rect_at clear_screen draw_text draw_digit
        blit blit_pose save_region restore_region present_objects scroll_background background
        camera fade
      ].freeze
      SOUND_KINDS = %i[play_song beep noise wave stop_wave enable_sound stop_music mixer].freeze
      CATEGORY_ORDER = %i[drawing sound logic].freeze

      def initialize(**weights)
        @weights = DEFAULT_WEIGHTS.merge(weights)
      end
    end
  end
end
