# frozen_string_literal: true
#
# GENERATED by tools/calibrate_cost_model.rb — do not edit by hand.
# Re-run that tool after changing the lowering of a priced op, and commit the diff.
# Each value is scanlines per op, measured on the emulated GBA timing model via
# gemba-core (emulated-cycle counts, not host wall-clock — the same on any machine).
module RubyGBA
  module IR
    class CostModel
      MEASURED_WEIGHTS = {
        op_step: 0.01928,
        loop_pass: 0.05936,
        op_mul: 0.01928,
        op_div: 0.08058,
        op_div_bit: 0.00313,
        op_div_const: 0.03215,
        op_mul_fix: 0.02573,
        op_div_fix: 0.25211,
        plot_pixel: 0.01606,
        plot_run_pixel: 0.01285,
        plot_run_address_step: 0.00321,
        blit_pixel: 0.03534,
        blit_wide_color: 0.00322,
        blit_row: 0.02249,
        blit_start: 0.02334,
        digit_pixel: 0.02058,
        digit_cell: 0.03770,
        digit_start: 0.12093,
        tearfree_digit_pixel: 0.05134,
        sound_write: 0.01606,
        mix_voice_sample: 0.03000,
        mix_overhead_sample: 0.01104,
        music_voice: 0.05438,
        dma_setup: 0.05340,
        dma_pixel: 0.00122,
        obj_write: 0.11726,
        scroll_write: 0.10425,
        obj_turn: 0.11752,
        obj_resize: 0.15460,
        camera_move: 0.08355,
        fade_set: 0.02570,
        save_write: 0.07025,
        tearfree_pair: 0.00322,
        tearfree_row: 0.00639,
        tearfree_edge: 0.01285,
        tearfree_moving_start: 0.09754,
        tearfree_rect_start: 0.02591,
        tearfree_fill_pixel: 0.00081,
        tearfree_engine_row: 0.05079,
        tearfree_engine_edge: 0.02241,
        tearfree_pixel: 0.03212,
        tearfree_glyph: 0.02229,
        overlap_pixel: 0.22491,
        fast_code_speedup: 2.64689,
      }.freeze
    end
  end
end
