# frozen_string_literal: true
#
# GENERATED by tools/calibrate_cost_model.rb — do not edit by hand.
# Re-run that tool after changing the lowering of a priced op, and commit the diff.
# Each value is scanlines per op, measured on the emulated GBA timing model via
# gemba-core (emulated-cycle counts, not host wall-clock — the same on any machine).
module RubyGBA
  module IR
    class CostModel
      MEASURED_WEIGHTS = {
        op_step: 0.01928,
        op_mul: 0.01928,
        op_div: 0.08696,
        op_div_const: 0.03215,
        op_mul_fix: 0.02573,
        op_div_fix: 0.25542,
        plot_pixel: 0.01606,
        sound_write: 0.01606,
        mix_voice_sample: 0.03000,
        mix_overhead_sample: 0.01104,
        music_voice: 0.05438,
        dma_setup: 0.04822,
        dma_pixel: 0.00122,
        obj_write: 0.11726,
        scroll_write: 0.10425,
        overlap_pixel: 0.22491,
      }.freeze
    end
  end
end
